version : 2

sources:
    - name: fraud_dataset
      description : "database online payment"
      database: strategic-kite-363002
      schema : fraud_dataset
      tables:
        - name : fraud_dataset_final

models:
  - name: source-table
    description: transformed table from batch processing table