version : 2

models:
  - name: fraud_data_only
    description: data froud only
    columns:
      - name: isFraud
        description: fraud detection
        tests:
          - accepted_values:
              values: [1,0]
